workspace "opencode-tridev" "Local-first wrapper that generates and launches a configured OpenCode CLI" {

    properties {
        "architecture.note" "A personal dev environment, not a product. One operator, one machine. scripts/opencode.sh reads .env and the T-Systems model catalog, writes opencode.json, then execs the OpenCode CLI. No server, no database, no deployment target."
        "model.tiers" "Tiers are declared, not routed. Two tiers are in actual use: Ollama local (free) and the T-Systems cloud hub. Automated model routing was considered and explicitly rejected, because a bash config generator has no visibility into the task it would be routing."
    }

    model {
        operator = person "Operator" "A single senior engineer. Runs everything locally." {
            tags "human"
        }

        brahma = person "Brahma" "Architect. Plans, writes ADRs and Structurizr diagrams. Writes docs/** and docs/adr/** only, never code." {
            tags "agent,architect"
        }

        vishnu = person "Vishnu" "Builder. Implements features and writes tests. Must not touch docs/**." {
            tags "agent,builder"
        }

        maheshwara = person "Maheshwara" "Finisher. Verifies the implementation against the plan, runs tests, cleans up and refactors. Requires the whole working tree exclusively." {
            tags "agent,finisher"
        }

        opencode = softwareSystem "OpenCode CLI" "The agent host. Loads the generated config, calls the model providers and spawns MCP servers. Not part of this repository." {
            tags "external,agent-host"
        }

        ollama = softwareSystem "Ollama" "Local model runtime serving qwen2.5-coder-tools:7b. Free, no data egress." {
            tags "local,external,tier-1"
        }

        tsystems = softwareSystem "T-Systems LLM Hub" "Cloud hub exposing about 40 models over an OpenAI-compatible API. Billed in EUR per token." {
            tags "cloud,external,tier-2,tier-3"
        }

        jira = softwareSystem "Atlassian Jira" "Issue tracker. Reached only through the Model Context Protocol, never called directly by the launcher." {
            tags "cloud,external"
        }

        tridev = softwareSystem "opencode-tridev" "The launcher. A 510 line bash script plus a generated config and a devbox definition. It exists to configure and start the OpenCode CLI." {
            tags "local,launcher"

            properties {
                "vcs" "None. There is no git repository; git init was considered and declined."
                "vcs.consequence" "No undo mechanism. A stray agent edit in the working tree is unrecoverable. This was explicitly accepted by the operator after being told."
                "isolation" "No git worktrees either. Parallel agent safety rests on disjoint writable path sets rather than on separate checkouts."
                "concurrency" "Agents must not run in parallel by default. Brahma and Vishnu may, because their writable paths are disjoint. Maheshwara always runs alone."
            }

            devbox = container "devbox.json" "Reproducible environment: nodejs 22, python 3.11, uv, git, curl. Defines the opencode and opencode-ollama scripts." "Devbox" {
                tags "environment"
            }

            launcher = container "scripts/opencode.sh" "The launcher. Loads .env, fetches the T-Systems model catalog, injects a hardcoded pricing severity table into each model name, generates opencode.json, merges AGENTS.md into the target folder, and starts the Ollama tool-call proxy." "Bash" {
                tags "launcher"
            }

            config = container "opencode.json" "Generated config: model, small_model, providers, the MCP server definition, plugins and skill paths. Overwritten on every run." "JSON" {
                tags "generated"
            }

            skills = container "skills-lock.json and .agents/skills" "Pinned skill bundles, regenerated by scripts/setup-opencode-skills.sh. Listed in .gitignore, so this is a build artifact rather than source." "JSON" {
                tags "generated"
            }

            env = container ".env" "Secrets: TSYSTEMS_OPENCODE_API_KEY, JIRA_URL, JIRA_USER_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT. Never committed." "Dotenv" {
                tags "local,secrets"
            }

            ollamaProxy = container "Ollama tool-call proxy" "OpenAI-compatible proxy on http://localhost:4198/v1 that adds tool calling to the local model. The launcher is written to start it alongside Ollama." "Node.js" {
                tags "local,proxy"

                properties {
                    "status" "Declared dependency, not a verified component. scripts/opencode.sh starts it via npm run ollama:serve in open-code/, but no ollama:serve script and no proxy source exist in the checked-in open-code/package.json. Port 4198 and this hop are load-bearing in opencode.json regardless."
                }
            }

            group "Jira MCP boundary" {
                mcpServer = container "Jira MCP server" "Local MCP server declared as type local with command uvx mcp-atlassian. Spawned on demand by the OpenCode CLI, not by the launcher, and handed the JIRA_* variables via .env." "Python via uvx" {
                    tags "local,mcp"
                }
            }
        }

        operator -> tridev "Runs the launcher from a devbox shell" "Shell"
        devbox -> launcher "Invokes as bash scripts/opencode.sh" "Shell"
        launcher -> env "Loads and exports the values" "Shell"
        launcher -> tsystems "Fetches GET /models once, to build the provider catalog" "HTTPS"
        launcher -> config "Regenerates on every run" "jq"
        launcher -> skills "Reads the lockfile and rewrites skills.paths" "jq"
        launcher -> opencode "Writes the config, then execs the CLI in the target directory" "Shell"
        launcher -> ollamaProxy "Starts it alongside Ollama, only when --ollama is passed" "Shell"
        operator -> skills "Regenerates the lockfile via scripts/setup-opencode-skills.sh" "Shell"

        config -> env "References values indirectly through env placeholders, so no secret is ever written into opencode.json" "JSON"
        config -> ollamaProxy "Points the ollama provider at http://localhost:4198/v1" "JSON"
        config -> tsystems "Declares about 40 models and the API key placeholder" "JSON"
        config -> mcpServer "Declares it as a local server running uvx mcp-atlassian" "JSON"

        opencode -> ollamaProxy "Sends inference and tool calls" "HTTP"
        opencode -> tsystems "Sends inference for cloud models, using the key from .env" "HTTPS"
        opencode -> mcpServer "Spawns on demand and speaks MCP over stdio" "stdio"
        ollamaProxy -> ollama "Forwards to the OpenAI-compatible endpoint and synthesises tool calls" "HTTP"
        mcpServer -> jira "Reads and writes issues" "HTTPS"

        tridev -> opencode "Configures and launches" "Shell"
        tridev -> ollama "Starts Ollama and the tool-call proxy, then polls port 4198" "Shell"
        tridev -> tsystems "Fetches the model catalog" "HTTPS"
        tridev -> jira "Indirect, via MCP. The launcher only writes the mcp-atlassian server definition into opencode.json; the server is spawned by the CLI and makes the actual call. No direct Jira API access." "MCP"
        operator -> tsystems "Pays the per-token EUR invoices" "Billing"

        operator -> brahma "Opens the task with" "Prompt"
        operator -> vishnu "Opens the task with" "Prompt"
        operator -> maheshwara "Opens the task with" "Prompt"
        brahma -> tridev "Plans and writes docs/** and docs/adr/**" "Files"
        vishnu -> tridev "Writes src/**, test/** and build files" "Files"
        maheshwara -> tridev "Verifies, tests and cleans up, needing the whole tree" "Files"
        brahma -> maheshwara "Hands over the plan" "Prompt"
        vishnu -> maheshwara "Reports the implementation" "Prompt"
    }

    views {
        systemContext tridev system-context "The launcher and the systems it reaches" {
            include *
            exclude brahma vishnu maheshwara
            autoLayout lr
            title "opencode-tridev - System Context"
        }

        container tridev container-view "How the launcher builds a configured OpenCode CLI" {
            include *
            exclude brahma vishnu maheshwara

            // ponytail: The system-level edges restate the container-level hops, and
            // Structurizr draws both in a container view. Excluded by expression so each hop
            // appears once. Limitation: this list is maintained by hand and is wrong the moment
            // a system-level edge is added or removed. Upgrade path: delete the exclusions and
            // the system-level edges together if the launcher ever stops reaching these systems
            // directly, rather than growing this list.
            exclude "tridev -> opencode" "tridev -> ollama" "tridev -> tsystems" "tridev -> jira"

            autoLayout lr
            title "opencode-tridev - Containers"
        }

        dynamic * agent-protocol "The parallel agent protocol and the two accepted trade-offs" {
            1: operator -> brahma "Opens the task: architect pass"
            1: operator -> vishnu "Opens the task: build pass"

            2: brahma -> tridev "Runs in parallel. Writes docs/** and docs/adr/** only. Must not touch src/**, test/** or build files."
            2: vishnu -> tridev "Runs in parallel. Writes src/**, test/** and build files. Must not touch docs/**."

            3: brahma -> maheshwara "Both complete: hands over the plan"
            3: vishnu -> maheshwara "Both complete: reports the implementation"

            4: maheshwara -> tridev "Runs alone. Verifies against the plan, runs tests, cleans up and refactors, needing exclusive use of the whole tree."

            autoLayout lr
            title "The parallel agent protocol"
        }

        styles {
            element "local" {
                background #dbe9f4
                stroke #1b6ca8
                color #000000
            }
            element "cloud" {
                background #f6e2d3
                stroke #c2570a
                color #000000
            }
            element "secrets" {
                border dashed
            }
            element "Group" {
                stroke #666666
            }
        }
    }
}
